name: Deploy Static Content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Directory Structure
        run: |
          echo "### Directory structure:"
          ls -R
          echo "### Current working directory:"
          pwd

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Static Files
        uses: actions/upload-pages-artifact@v3
        with:
          # Correct paths to static and templates directories
          path: |
            cb/static
            cb/templates

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
